builds:
  - id: pushbits
    main: ./cmd/pushbits
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64

checksum:
  algorithm: sha256

archives:
  - id: pushbits
    builds:
      - pushbits
    format: tar.gz
