# A sample configuration for PushBits.

# Populated fields contain their default value.

# Required fields are marked with [required].

debug: false

http:
    # The address to listen on. If empty, listens on all available IP addresses of the system.
    listenaddress: ''

    # The port to listen on.
    port: 8080

    # What proxies to trust.
    trustedproxies: []

    # Filename of the TLS certificate.
    certfile: ''

    # Filename of the TLS private key.
    keyfile: ''

database:
    # Currently sqlite3, mysql, and postgres are supported.
    dialect: 'sqlite3'

    # - For sqlite3, specify the database file.
    # - For mysql specify the connection string. See details at https://github.com/go-sql-driver/mysql#dsn-data-source-name
    # - For postgres, see https://github.com/jackc/pgx.
    #   Also consider the canonical docs at https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING.
    connection: 'pushbits.db'

admin:
    # The username of the initial admin.
    name: 'admin'

    # The password of the initial admin.
    password: 'admin'

    # The Matrix ID of the initial admin, where notifications for that admin are sent to.
    # [required]
    matrixid: ''

matrix:
    # The Matrix server to use for sending notifications.
    homeserver: 'https://matrix.org'

    # The username of the Matrix account to send notifications from.
    # [required]
    username: ''

    # The password of the Matrix account to send notifications from.
    # [required]
    password: ''

security:
    # Wether or not to check for weak passwords using HIBP.
    checkhibp: false

crypto:
    # Configuration of the KDF for password storage. Do not change unless you know what you are doing!
    argon2:
        memory: 131072
        iterations: 4
        parallelism: 4
        saltlength: 16
        keylength: 32

formatting:
    # Whether to use colored titles based on the message priority (<0: grey, 0-3: default, 4-10: yellow, 10-20: orange, >20: red).
    coloredtitle: false

# This settings are only relevant if you want to use PushBits with alertmanager
alertmanager:
    # The name of the entry in the alerts annotations or lables that should be used for the title
    annotationtitle: title
    # The name of the entry in the alerts annotations or labels that should be used for the message
    annotationmessage: message

repairbehavior:
    # Reset the room's name to what was initially set by PushBits.
    resetroomname: true
    # Reset the room's topic to what was initially set by PushBits.
    resetroomtopic: true
