name: Test

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
      - '!v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

env:
  PB_BUILD_VERSION: pipeline-${{ github.sha }}

jobs:
  test_build:
    name: Test and build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Export GOBIN
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.6'

      - name: Install dependencies
        run: make setup

      - name: Run tests
        run: make test

      - name: Build
        run: make build
