name: Test

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
      - '!v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

env:
  PB_BUILD_VERSION: pipeline-${{ github.sha }}

jobs:
  test_build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Export GOBIN
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: make setup

      - name: Run tests
        run: |
          source $(poetry env info --path)/bin/activate
          make test

      - name: Build
        run: make build
